version: '3'
services: 
  devcontainer: 
    volumes: 
      - ..:/workspace:cached
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /mnt/wslg:/mnt/wslg
      - /root/.gazebo/models/:/root/.gazebo/models/
      - $HOME/.Xauthority:/tmp/.Xauthority:rw
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.Xauthority

    cap_add:
      - SYS_PTRACE  
    command: /bin/sh -c "while sleep 1000; do :; done"
 
    build:
      context: .
      dockerfile: Dockerfile.devcontainer 

    network_mode: "host"
 